// Customizer const
export const TOGGLE_COLLAPSED_NAV = "TOGGLE_COLLAPSE_MENU";
export const WINDOW_WIDTH = "WINDOW-WIDTH";
export const SWITCH_LANGUAGE = "SWITCH-LANGUAGE";

//Contact Module const
export const FETCH_START = "fetch_start";
export const FETCH_SUCCESS = "fetch_success";
export const FETCH_ERROR = "fetch_error";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
export const ON_SHOW_LOADER = "ON_SHOW_LOADER";
export const ON_HIDE_LOADER = "ON_HIDE_LOADER";

export const SHOW_MESSAGE_ERROR = "SHOW_MESSAGE_ERROR";
export const SHOW_MESSAGE_SUCCESS = "SHOW_MESSAGE_SUCCESS";
export const SHOW_MESSAGE_HIDE = "SHOW_MESSAGE_HIDE";

//Auth const
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNIN_GOOGLE_USER = "SIGNIN_GOOGLE_USER";
export const SIGNIN_GOOGLE_USER_SUCCESS = "SIGNIN_GOOGLE_USER_SUCCESS";
export const SIGNIN_FACEBOOK_USER = "SIGNIN_FACEBOOK_USER";
export const SIGNIN_FACEBOOK_USER_SUCCESS = "SIGNIN_FACEBOOK_USER_SUCCESS";
export const SIGNIN_TWITTER_USER = "SIGNIN_TWITTER_USER";
export const SIGNIN_TWITTER_USER_SUCCESS = "SIGNIN_TWITTER_USER_SUCCESS";
export const SIGNIN_GITHUB_USER = "SIGNIN_GITHUB_USER";
export const SIGNIN_GITHUB_USER_SUCCESS = "signin_github_user_success";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const INIT_URL = "INIT_URL";
export const USER_DATA = "user_data";
export const USER_DATA_PARKING = "USER_DATA_PARKING";
export const USER_TOKEN_SET = "user_token_set";
export const GET_IP = "GET_IP";
export const LOAD_MENU_LIST = "LOAD_MENU_LIST";

// auth stamp
export const LOGIN_WEBSTAMP = "LOGIN_WEBSTAMP";
export const LOAD_USER_WEBSTAMP = "LOAD_USER_WEBSTAMP";

// visitor
export const LOAD_VISITOR_DETAIL = "LOAD_VISITOR_DETAIL";
export const REMOVE_DATA_VISITOR = "REMOVE_DATA_VISITOR";
export const LOAD_INOUT_TRANDETAIL = "LOAD_INOUT_TRANDETAIL";
export const REMOVE_INOUT_TRANDETAIL = "REMOVE_INOUT_TRANDETAIL";
//Stamp insert
export const INSERT_STAMP_CODE = "INSERT_STAMP_CODE";
// Active Stamp
export const LOAD_ACTIVE_STAMP = "LOAD_ACTIVE_STAMP";
export const LOAD_CHANGE_STAMP = "LOAD_CHANGE_STAMP";
export const UPDATE_STAMP = "UPDATE_STAMP";
// member stamp
export const LOAD_MEMBER_LIST = "LOAD_MEMBER_LIST";

export const LOAD_MEMBER_DEPARTMENT = "LOAD_MEMBER_DEPARTMENT";
export const LOAD_DEPARTMENT = "LOAD_DEPARTMENT";
export const LOAD_CARD_TYPE = "LOAD_CARD_TYPE";
export const LOAD_MEMBER_TRAN_INOUT = "LOAD_MEMBER_TRAN_INOUT";
export const LOAD_MEMNER_COMPANY = "LOAD_MEMNER_COMPANY";
export const LOAD_ADMIN_RESET_PASSWORD = "LOAD_ADMIN_RESET_PASSWORD";

//Require Change Member
export const LOAD_REQIRECHENG_MEMNER_LIST = "LOAD_REQIRECHENG_MEMNER_LIST";
export const LOAD_REQUIRE_CARTYPE = "LOAD_REQUIRE_CARTYPE";
export const LOAD_PAYMENT_LIST = "LOAD_PAYMENT_LIST";
export const LOAD_CONTAC_TYPE_LIST = "LOAD_CONTAC_TYPE_LIST";
//Report Stamp
export const LOAD_STAMP_CODE_ALL = "LOAD_STAMP_CODE_ALL";
export const LOAD_DEPARTMENT_LIST = "LOAD_DEPARTMENT_LIST";
export const LOAD_STAMP_REPORT = "LOAD_STAMP_REPORT";
export const LOAD_CUSTOM_LIST = "LOAD_CUSTOM_LIST";

export const LOAD_CUSTOM_REPORT = "LOAD_CUSTOM_REPORT";
export const LOAD_STAMP_BY_STAMP_REPORT = "LOAD_STAMP_BY_STAMP_REPORT";
export const LOAD_ADMIN_LIST = "LOAD_ADMIN_LIST";
export const LOAD_STAMP_BY_USER = "LOAD_STAMP_BY_USER";
export const LOAD_SUMMERY_STAMP_BY_DEPARTMENT =
  "LOAD_SUMMERY_STAMP_BY_DEPARTMENT";
export const LOAD_SUMARY_BY_STAMP = "LOAD_SUMARY_BY_STAMP";

export const ADD_REQUIRE_MEMBER = "ADD_REQUIRE_MEMBER";
export const LOAD_DOCLIST = "LOAD_DOCLIST";
export const SEND_EMAIL_UPLOAD_FILE = "SEND_EMAIL_UPLOAD_FILE";
export const GET_MEMBER_NAME_LIST = "GET_MEMBER_NAME_LIST";
export const GET_USER_INFO = "GET_USER_INFO";
export const LOAD_USER_ADMIN = "LOAD_USER_ADMIN";
export const ADD_USER_ADMIN = "ADD_USER_ADMIN";
export const ADMIN_LEVEL_LIST = "ADMIN_LEVEL_LIST";
export const LOAD_USER_DETAIL = "LOAD_USER_DETAIL";
export const LOAD_GET_MESSAGE_WEB = "LOAD_GET_MESSAGE_WEB";
//Parking API
export const LOAD_ACTIVE_STAMP_PARKING = "LOAD_ACTIVE_STAMP_PARKING";
export const LOAD_STAMP_REPORT_PARKING = "LOAD_STAMP_REPORT_PARKING";
export const LOAD_DEPARTMENT_LIST_PARKING = "LOAD_DEPARTMENT_LIST_PARKING";
export const LOAD_STAMP_CODE_ALL_PARKING = "LOAD_STAMP_CODE_ALL_PARKING";

export const LOAD_STAMP_BY_COSTOM_PARKING = "LOAD_STAMP_BY_COSTOM_PARKING";
export const LOAD_STAMP_BY_STAMP_PARKING = "LOAD_STAMP_BY_STAMP_PARKING";
export const LOAD_STAMP_BY_USER_PARKING = "LOAD_STAMP_BY_USER_PARKING";

export const LOAD_ADMIN_LIST_PARKING = "LOAD_ADMIN_LIST_PARKING";
export const LOAD_STAMP_REPORT_BY_STAMP_PARKING =
  "LOAD_STAMP_REPORT_BY_STAMP_PARKING";

export const LOAD_ADMIN_SYSTME_PARKING = "LOAD_ADMIN_SYSTME_PARKING";
export const LOAD_STAMP_REPORT_BY_DEPARTMENT_PARKING =
  "LOAD_STAMP_REPORT_BY_DEPARTMENT_PARKING";
